version: '4'

networks:
    laravel:

services:
    site:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
        container_name: nginx
        ports:
            - 8085:80
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - mysql
            - mailhog
        networks:
            - laravel

    mysql:
        image: mariadb:10.6
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - laravel

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        container_name: composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        user: ${USER:-youruser}
        entrypoint: ['composer', '--ignore-platform-reqs']
        networks:
            - laravel

    npm:
        image: node:20.5
        container_name: npm
        volumes:
            - ./:/var/www/html
        ports:
            - 3000:3000
            - 3001:3001
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    artisan:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - laravel
